allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - expo-image-manipulator@57.0.9
  - expo-image-picker@57.0.9
