allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - expo-image-manipulator@57.0.9
  - expo-image-picker@57.0.9
  - '@expo/ui@57.0.18'
  - expo-widgets@57.0.19
patchedDependencies:
  react-native-android-widget@0.22.1: patches/react-native-android-widget@0.22.1.patch
